services:
  sonarqube:
    hostname: sonarqube
    container_name: sonarqube
    #image: sonarqube:10.6.0-community
    # LTS版本
    image: sonarqube:9.9.6-community
    # 下面的内核参数请在宿主机上执行
    # sysctls:
    #   # TCP可以排队的最大连接请求数
    #   net.core.somaxconn: 4096
    #   # 单个进程可以拥有的虚拟内存区域的数量
    #   vm.max_map_count: 262184
    privileged: true 
    restart: always  
    depends_on:
    - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_pdf:/opt/sonarqube/pdf-files
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    hostname: postgresql
    container_name: postgresql
    privileged: true
    restart: always
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data